# Generated by Django 5.1.4 on 2025-03-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_intensity_speechfeature_pause_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeechFeature',
        ),
    ]
